"""initial leads and lead_events tables

Revision ID: cbc68d66be23
Revises: 
Create Date: 2026-08-15 12:51:23.016035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbc68d66be23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'scheduled', 'done', 'canceled', 'spam', name='leadstatus', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('contact_channel', sa.Enum('whatsapp', 'call', 'telegram', name='contactchannel', native_enum=False, length=20), nullable=False),
    sa.Column('service_type', sa.Enum('maintenance', 'general', 'post_renovation', 'post_move', name='servicetype', native_enum=False, length=20), nullable=False),
    sa.Column('property_type', sa.Enum('apartment', 'house', 'office', name='propertytype', native_enum=False, length=20), nullable=False),
    sa.Column('area_m2', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('addons', sa.JSON(), nullable=False),
    sa.Column('urgency', sa.Enum('normal', 'urgent', name='urgency', native_enum=False, length=20), nullable=False),
    sa.Column('frequency', sa.Enum('once', 'monthly', 'biweekly', 'weekly', name='frequency', native_enum=False, length=20), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('lang', sa.Enum('ru', 'ky', 'en', name='lang', native_enum=False, length=8), nullable=False),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_medium', sa.String(length=200), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('utm_content', sa.String(length=200), nullable=True),
    sa.Column('utm_term', sa.String(length=200), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('landing_page', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_index('ix_leads_status_created_at', 'leads', ['status', 'created_at'], unique=False)
    op.create_table('lead_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index('ix_leads_status_created_at', table_name='leads')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
